apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-aks-k8s-cluster
  region: us-east-2
  version: "1.28"
managedNodeGroups:
  - instanceType: t3.medium
    amiFamily: AmazonLinux2
    name: eks-aks-nodegroup
    desiredCapacity: 2
    minSize: 2
    maxSize: 4